# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1151, 740)
        MainWindow.setMinimumSize(QtCore.QSize(1151, 740))
        MainWindow.setMaximumSize(QtCore.QSize(1151, 740))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(127, 80))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 731, 631))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 32, 711, 591))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(135, 0))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(135, 0))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(135, 16777215))
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line_url = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_url.setText("")
        self.line_url.setObjectName("line_url")
        self.verticalLayout_2.addWidget(self.line_url)
        self.line_dir = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_dir.setObjectName("line_dir")
        self.verticalLayout_2.addWidget(self.line_dir)
        self.line_filename = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_filename.setObjectName("line_filename")
        self.verticalLayout_2.addWidget(self.line_filename)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.push_url = QtWidgets.QPushButton(self.layoutWidget)
        self.push_url.setObjectName("push_url")
        self.verticalLayout_3.addWidget(self.push_url)
        self.push_browse = QtWidgets.QPushButton(self.layoutWidget)
        self.push_browse.setObjectName("push_browse")
        self.verticalLayout_3.addWidget(self.push_browse)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.check_best = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_best.setObjectName("check_best")
        self.horizontalLayout_3.addWidget(self.check_best)
        self.check_thumbnail = QtWidgets.QCheckBox(self.layoutWidget)
        self.check_thumbnail.setObjectName("check_thumbnail")
        self.horizontalLayout_3.addWidget(self.check_thumbnail)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.stream_tree = QtWidgets.QTreeWidget(self.layoutWidget)
        self.stream_tree.setLineWidth(1)
        self.stream_tree.setObjectName("stream_tree")
        self.verticalLayout_4.addWidget(self.stream_tree)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(750, 0, 371, 631))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_thumbnail = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_thumbnail.sizePolicy().hasHeightForWidth())
        self.label_thumbnail.setSizePolicy(sizePolicy)
        self.label_thumbnail.setMinimumSize(QtCore.QSize(345, 230))
        self.label_thumbnail.setMaximumSize(QtCore.QSize(345, 230))
        self.label_thumbnail.setAutoFillBackground(False)
        self.label_thumbnail.setText("")
        self.label_thumbnail.setObjectName("label_thumbnail")
        self.verticalLayout_6.addWidget(self.label_thumbnail)
        self.label_title = QtWidgets.QLabel(self.groupBox_2)
        self.label_title.setText("")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout_6.addWidget(self.label_title)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_eta = QtWidgets.QLabel(self.groupBox_2)
        self.label_eta.setText("")
        self.label_eta.setObjectName("label_eta")
        self.gridLayout_2.addWidget(self.label_eta, 1, 1, 1, 1)
        self.label_size = QtWidgets.QLabel(self.groupBox_2)
        self.label_size.setText("")
        self.label_size.setObjectName("label_size")
        self.gridLayout_2.addWidget(self.label_size, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_speed = QtWidgets.QLabel(self.groupBox_2)
        self.label_speed.setText("")
        self.label_speed.setObjectName("label_speed")
        self.gridLayout_2.addWidget(self.label_speed, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.progress_single = QtWidgets.QProgressBar(self.groupBox_2)
        self.progress_single.setMaximum(1000)
        self.progress_single.setProperty("value", 0)
        self.progress_single.setObjectName("progress_single")
        self.verticalLayout_5.addWidget(self.progress_single)
        self.progress_total = QtWidgets.QProgressBar(self.groupBox_2)
        self.progress_total.setMaximum(1000)
        self.progress_total.setProperty("value", 0)
        self.progress_total.setObjectName("progress_total")
        self.verticalLayout_5.addWidget(self.progress_total)
        self.push_download = QtWidgets.QPushButton(self.groupBox_2)
        self.push_download.setEnabled(False)
        self.push_download.setObjectName("push_download")
        self.verticalLayout_5.addWidget(self.push_download)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 0, 711, 631))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 40, 691, 581))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_10.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_10.addWidget(self.label_12)
        self.horizontalLayout_6.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.line_batchfile = QtWidgets.QLineEdit(self.layoutWidget1)
        self.line_batchfile.setObjectName("line_batchfile")
        self.verticalLayout_11.addWidget(self.line_batchfile)
        self.line_output_batch = QtWidgets.QLineEdit(self.layoutWidget1)
        self.line_output_batch.setObjectName("line_output_batch")
        self.verticalLayout_11.addWidget(self.line_output_batch)
        self.horizontalLayout_6.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.push_batch_select = QtWidgets.QPushButton(self.layoutWidget1)
        self.push_batch_select.setObjectName("push_batch_select")
        self.verticalLayout_12.addWidget(self.push_batch_select)
        self.push_batch_brows = QtWidgets.QPushButton(self.layoutWidget1)
        self.push_batch_brows.setObjectName("push_batch_brows")
        self.verticalLayout_12.addWidget(self.push_batch_brows)
        self.horizontalLayout_6.addLayout(self.verticalLayout_12)
        self.verticalLayout_13.addLayout(self.horizontalLayout_6)
        self.groupBox_4 = QtWidgets.QGroupBox(self.layoutWidget1)
        self.groupBox_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radio_best = QtWidgets.QRadioButton(self.groupBox_4)
        self.radio_best.setChecked(True)
        self.radio_best.setObjectName("radio_best")
        self.horizontalLayout_4.addWidget(self.radio_best)
        self.radio_worst = QtWidgets.QRadioButton(self.groupBox_4)
        self.radio_worst.setObjectName("radio_worst")
        self.horizontalLayout_4.addWidget(self.radio_worst)
        self.verticalLayout_13.addWidget(self.groupBox_4)
        self.groupBox_7 = QtWidgets.QGroupBox(self.layoutWidget1)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.check_hfolder = QtWidgets.QCheckBox(self.groupBox_7)
        self.check_hfolder.setObjectName("check_hfolder")
        self.horizontalLayout_5.addWidget(self.check_hfolder)
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_7)
        self.label_14.setEnabled(False)
        self.label_14.setMinimumSize(QtCore.QSize(120, 0))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        self.combo_folder_name = QtWidgets.QComboBox(self.groupBox_7)
        self.combo_folder_name.setEnabled(False)
        self.combo_folder_name.setMinimumSize(QtCore.QSize(100, 0))
        self.combo_folder_name.setObjectName("combo_folder_name")
        self.combo_folder_name.addItem("")
        self.combo_folder_name.addItem("")
        self.horizontalLayout_5.addWidget(self.combo_folder_name)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.verticalLayout_13.addWidget(self.groupBox_7)
        self.list_urls = QtWidgets.QListWidget(self.layoutWidget1)
        self.list_urls.setObjectName("list_urls")
        self.verticalLayout_13.addWidget(self.list_urls)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_6.setGeometry(QtCore.QRect(750, 0, 371, 631))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_thumbnail_2 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_thumbnail_2.sizePolicy().hasHeightForWidth())
        self.label_thumbnail_2.setSizePolicy(sizePolicy)
        self.label_thumbnail_2.setMinimumSize(QtCore.QSize(345, 230))
        self.label_thumbnail_2.setMaximumSize(QtCore.QSize(345, 230))
        self.label_thumbnail_2.setText("")
        self.label_thumbnail_2.setObjectName("label_thumbnail_2")
        self.verticalLayout_7.addWidget(self.label_thumbnail_2)
        self.label_title_2 = QtWidgets.QLabel(self.groupBox_6)
        self.label_title_2.setText("")
        self.label_title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_2.setObjectName("label_title_2")
        self.verticalLayout_7.addWidget(self.label_title_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem3)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox_6)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_eta_2 = QtWidgets.QLabel(self.groupBox_6)
        self.label_eta_2.setText("")
        self.label_eta_2.setObjectName("label_eta_2")
        self.gridLayout_3.addWidget(self.label_eta_2, 1, 1, 1, 1)
        self.label_size_2 = QtWidgets.QLabel(self.groupBox_6)
        self.label_size_2.setText("")
        self.label_size_2.setObjectName("label_size_2")
        self.gridLayout_3.addWidget(self.label_size_2, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_speed_2 = QtWidgets.QLabel(self.groupBox_6)
        self.label_speed_2.setText("")
        self.label_speed_2.setObjectName("label_speed_2")
        self.gridLayout_3.addWidget(self.label_speed_2, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_10.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_3)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.progress_single_2 = QtWidgets.QProgressBar(self.groupBox_6)
        self.progress_single_2.setMaximum(1000)
        self.progress_single_2.setProperty("value", 0)
        self.progress_single_2.setObjectName("progress_single_2")
        self.verticalLayout_8.addWidget(self.progress_single_2)
        self.progress_total_2 = QtWidgets.QProgressBar(self.groupBox_6)
        self.progress_total_2.setMaximum(1000)
        self.progress_total_2.setProperty("value", 0)
        self.progress_total_2.setObjectName("progress_total_2")
        self.verticalLayout_8.addWidget(self.progress_total_2)
        self.push_download_batch = QtWidgets.QPushButton(self.groupBox_6)
        self.push_download_batch.setObjectName("push_download_batch")
        self.verticalLayout_8.addWidget(self.push_download_batch)
        self.verticalLayout_7.addLayout(self.verticalLayout_8)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 461, 261))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 30, 441, 71))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.line_proxy = QtWidgets.QLineEdit(self.layoutWidget2)
        self.line_proxy.setText("")
        self.line_proxy.setObjectName("line_proxy")
        self.horizontalLayout_2.addWidget(self.line_proxy)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_13.setLineWidth(2)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_9.addWidget(self.label_13)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1151, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RT YoutubeDownloader"))
        self.label.setText(_translate("MainWindow", "Youtube URL"))
        self.label_2.setText(_translate("MainWindow", "Output Dir"))
        self.label_3.setText(_translate("MainWindow", "Filename Overwrite"))
        self.push_url.setText(_translate("MainWindow", "Load URL"))
        self.push_browse.setText(_translate("MainWindow", "Browse"))
        self.check_best.setText(_translate("MainWindow", "Download Best"))
        self.check_thumbnail.setText(_translate("MainWindow", "Save Thumbnail"))
        self.stream_tree.headerItem().setText(0, _translate("MainWindow", "Available Streams"))
        self.label_7.setText(_translate("MainWindow", "File Size"))
        self.label_6.setText(_translate("MainWindow", "ETA (current)"))
        self.label_5.setText(_translate("MainWindow", "Speed"))
        self.push_download.setText(_translate("MainWindow", "Downlod (Load URL First)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Downloader"))
        self.label_11.setText(_translate("MainWindow", "Batch File"))
        self.label_12.setText(_translate("MainWindow", "Output Dir"))
        self.push_batch_select.setText(_translate("MainWindow", "Select"))
        self.push_batch_brows.setText(_translate("MainWindow", "Browse"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Quality"))
        self.radio_best.setText(_translate("MainWindow", "Best"))
        self.radio_worst.setText(_translate("MainWindow", "Worst"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Other Batch Options"))
        self.check_hfolder.setText(_translate("MainWindow", "Download in separate folders"))
        self.label_14.setText(_translate("MainWindow", "Folder name"))
        self.combo_folder_name.setItemText(0, _translate("MainWindow", "Title"))
        self.combo_folder_name.setItemText(1, _translate("MainWindow", "Id"))
        self.label_8.setText(_translate("MainWindow", "File Size"))
        self.label_9.setText(_translate("MainWindow", "ETA (current)"))
        self.label_10.setText(_translate("MainWindow", "Speed"))
        self.push_download_batch.setText(_translate("MainWindow", "Download"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Batch Download"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Network"))
        self.label_4.setText(_translate("MainWindow", "Proxy"))
        self.label_13.setText(_translate("MainWindow", "Help: proxy-type://address:port\n"
"Example: socks5://127.0.0.1:1080"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Options"))
